// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsn16fTbq4v9h39lshQTLMn__aXSSqT0s',
    appId: '1:940306583547:web:c9d105442076b0214b055e',
    messagingSenderId: '940306583547',
    projectId: 'spacechat-41a38',
    authDomain: 'spacechat-41a38.firebaseapp.com',
    databaseURL: 'https://spacechat-41a38-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'spacechat-41a38.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0yaypK4ySn7_P332fGNiYm687h4tsIrw',
    appId: '1:940306583547:android:aca232ea8579fbf64b055e',
    messagingSenderId: '940306583547',
    projectId: 'spacechat-41a38',
    databaseURL: 'https://spacechat-41a38-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'spacechat-41a38.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCskDGryU8Cd9ju2A2hZk1c8TTnZKI5dCs',
    appId: '1:940306583547:ios:077b3f9f342b18d94b055e',
    messagingSenderId: '940306583547',
    projectId: 'spacechat-41a38',
    databaseURL: 'https://spacechat-41a38-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'spacechat-41a38.appspot.com',
    iosClientId: '940306583547-e6sg415q8id7fcbuq7mtjha8qt49i826.apps.googleusercontent.com',
    iosBundleId: 'com.example.spaceChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCskDGryU8Cd9ju2A2hZk1c8TTnZKI5dCs',
    appId: '1:940306583547:ios:04ca56209617885f4b055e',
    messagingSenderId: '940306583547',
    projectId: 'spacechat-41a38',
    databaseURL: 'https://spacechat-41a38-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'spacechat-41a38.appspot.com',
    iosClientId: '940306583547-16u82c7a05q13dk6122nal89j10jhqqg.apps.googleusercontent.com',
    iosBundleId: 'com.example.spaceChat.RunnerTests',
  );
}
